#!/bin/bash

function install_php() {
    check_libmcrypt
    check_icu
    check_bison
    check_re2c

    local pkg=php-${PHP_VERSION}.tar.gz

    mkdir -p ${BUILD_DIR}
    mkdir -p ${ROOT_DIR}/etc/php5/conf.d
    pushd ${BUILD_DIR}

    # Get archive
    download_and_unpack ${pkg} http://www.php.net/get/${pkg}/from/us1.php.net/mirror
    pushd php-${PHP_VERSION}

    if [[ ! -f config.log || `tail -n 1 config.log | tr -d '\n'` !=  'configure: exit 0' ]]; then
        echo "Configuring PHP."
        ./configure \
            --with-libdir=lib64 \
            --prefix=${ROOT_DIR}/php5 \
            --with-config-file-path=${ROOT_DIR}/etc/php5/ \
            --with-config-file-scan-dir=${ROOT_DIR}/etc/php5/conf.d/ \
            --with-icu-dir=${ROOT_DIR}/libs \
            --with-mcrypt=${ROOT_DIR}/libs \
            --with-layout=PHP \
            --with-pear \
            --with-pgsql \
            --with-mysqli \
            --with-pdo-mysql \
            --with-pdo-pgsql \
            --enable-pdo \
            --with-pdo-sqlite \
            --with-sqlite3 \
            --with-openssl \
            --with-zlib-dir \
            --with-iconv-dir \
            --with-freetype-dir \
            --with-jpeg-dir \
            --with-png-dir \
            --with-zlib \
            --with-bz2 \
            --with-libxml-dir \
            --with-curl \
            --with-gd \
            --with-xsl \
            --with-xmlrpc \
            --with-mhash \
            --with-gettext \
            --with-readline \
            --with-kerberos \
            --with-pcre-regex \
            --enable-json \
            --enable-bcmath \
            --enable-cli \
            --enable-calendar \
            --enable-dba \
            --enable-wddx \
            --enable-inline-optimization \
            --enable-simplexml \
            --enable-filter \
            --enable-ftp \
            --enable-tokenizer \
            --enable-dom \
            --enable-exif \
            --enable-mbregex \
            --enable-fpm \
            --enable-mbstring \
            --enable-gd-native-ttf \
            --enable-xml \
            --enable-xmlwriter \
            --enable-xmlreader \
            --enable-pcntl \
            --enable-sockets \
            --enable-zip \
            --enable-soap \
            --enable-shmop \
            --enable-sysvsem \
            --enable-sysvshm \
            --enable-sysvmsg \
            --enable-intl \
            --enable-maintainer-zts \
            --enable-opcache \
            --enable-phar=shared \
            --disable-debug \
            --disable-fileinfo \
            --disable-ipv6 \
            --disable-rpath
    fi

    echo "Compiling PHP."
    make install

    # Copy configuration file
    local ini=${TEMPLATE_DIR}/php.ini.tmpl
    if [[ -e  ${ini} ]]; then
        echo "Copy ini for ${1}."
        yes | cp ${ini} ${ROOT_DIR}/etc/php5/php.ini
    else
        echo "Copy php.ini from php.ini-production."
        yes | cp php.ini-production ${ROOT_DIR}/etc/php5/php.ini
    fi
    local ini=${TEMPLATE_DIR}/php_extra.ini.tmpl
    if [[ -e  ${ini} ]]; then
        echo "Copy ini for ${1}."
        yes | cp ${ini} ${ROOT_DIR}/etc/php5/conf.d/php_extra.ini
    fi

    echo "Cleaning build directory."
    popd
    popd
    rm -rf ${BUILD_DIR}
}

function check_php() {
    local php_bin=${ROOT_DIR}/php5/bin/php

    if [[ ! -e  ${php_bin} ]]; then
        echo "PHP not installed."
        install_php
    else
        local php_version=`${php_bin} -r "echo phpversion();"`

        if [[ ${PHP_VERSION} != ${php_version} ]]; then
            echo "PHP old, version: ${php_version}."
            install_php
        else
            echo "PHP up to date, version: ${php_version}."
        fi
    fi
}

function install_pecl() {
    if [ -z "${1}" ] || [ -z "${2}" ]; then
        echo "check_pecl: expected two arguments"
        return 1
    fi

    local pkg=${1}-${2}.tgz

    mkdir -p ${BUILD_DIR}
    pushd ${BUILD_DIR}

    # Get archive
    download_and_unpack ${pkg} http://pecl.php.net/get/${pkg}
    pushd ${1}-${2}

    echo "Configuring ${1}."
    ${ROOT_DIR}/php5/bin/phpize -clean
    ./configure \
        --with-php-config=${ROOT_DIR}/php5/bin/php-config \
        ${3}

    echo "Compiling ${1}."
    make install

    # Copy configuration files
    local ini=${TEMPLATE_DIR}/pecl/${1,,}.ini.tmpl
    if [[ -e  ${ini} ]]; then
        echo "Copy ini for ${1}."
        yes | cp ${ini} ${ROOT_DIR}/etc/php5/conf.d/${1,,}.ini
    fi

    echo "Cleaning build directory."
    popd
    popd
    rm -rf ${BUILD_DIR}
}

function check_pecl() {
    if [ -z "${1}" ] || [ -z "${2}" ]; then
        echo "check_pecl: expected two arguments"
        return 1
    fi

    local php_bin=${ROOT_DIR}/php5/bin/php
    local pecl_version=`${php_bin} -r "echo phpversion('${1}');"`

    if [[ ${2} != ${pecl_version} ]]; then
        echo "PHP pecl ${1} not installed or old version ${pecl_version}."
        install_pecl ${1} ${2} ${3}
    else
        echo "PHP pecl ${1} up to date, version: ${2}."
    fi
}
